#!/bin/bash -eu
set -o pipefail

logPrefix="$(basename "$0")"
log() {
  echo "[$logPrefix] [$(date)] $*"
}

suites="${1-}"

shutdown_docker_containers() {
  if [[ -n "${couchDockerContainer-}" ]]; then
		log "Shutting down couch docker container..."
    docker kill "$couchDockerContainer" || log "WARN: failed to shut down couch docker container; maybe it never started?"
  fi
}

log "Starting dev server..."
SERVER="pouchdb-express-router" # TODO what is this doing?
export COUCH_HOST="http://admin:password@127.0.0.1:5984" 

rm .dev-server-ready || true
CLIENT="node" npx node ./scripts/start-dev-server-for-continuous-perf.js &

log "Starting couch..."
couchDockerContainer="couchdb-$(date +%s)-$RANDOM"
trap shutdown_docker_containers EXIT
docker run -d --rm -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -it --name "$couchDockerContainer" -p 5984:5984 trivago/couchdb-cors:latest &

./wait-for-it.sh localhost:5984
log "Couch started OK :-)"

echo -n "[$logPrefix] [$(date)] Waiting for pouch to build..."
timeout 30 bash -c 'while ! [[ -f .dev-server-ready ]]; do echo -n .; sleep 1; done'
echo
log "Pouch started OK :-)"

# FIXME none of the code above actually works for starting pouch or the local server
# so to make up for it, we don't run tests until the user says they're ready
read -p "Press enter to run tests for first time... " -s

while true; do
	runstamp="$(date -Iseconds | head -c-7)"
  resultsDir="perf-test-results/$runstamp"
  mkdir -p "$resultsDir"
  ./scripts/playwright-perf-test "$resultsDir" idb       basics
  ./scripts/playwright-perf-test "$resultsDir" indexeddb basics
  log "Results written to: $resultsDir"

	./scripts/compare-perf-results "$runstamp"
  echo
  
  read -p "Press enter to run tests again... " -s
  echo
done
