#!/bin/bash -eu
set -o pipefail

logPrefix="$(basename "$0")"
log() {
  echo "[$logPrefix] [$(date)] $*"
}

suites="${1-}"

shutdown_docker_containers() {
  if [[ -n "${couchDockerContainer-}" ]]; then
    log "Shutting down couch docker container..."
    docker kill "$couchDockerContainer" || log "WARN: failed to shut down couch docker container; maybe it never started?"
  fi
}

log "Starting dev server..."
SERVER="pouchdb-express-router" # TODO what is this doing?
export COUCH_HOST="http://admin:password@127.0.0.1:5984" 

rm .dev-server-ready || true # maybe do this inside the script
//CLIENT="node" npx nodemon -w ./packages/node_modules/ -w ./tests/performance/ ./scripts/start-dev-server-for-continuous-perf.js &
# I'm really not sure nodemon is working reliably...
CLIENT="node" node ./scripts/start-dev-server-for-continuous-perf.js &

log "Starting couch..."
couchDockerContainer="couchdb-$(date +%s)-$RANDOM"
trap shutdown_docker_containers EXIT
docker run -d --rm -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -it --name "$couchDockerContainer" -p 5984:5984 trivago/couchdb-cors:latest &

./wait-for-it.sh localhost:5984
log "Couch started OK :-)"

log "Waiting for pouch to build..."
timeout 60 bash -c 'while ! [[ -f .dev-server-ready ]]; do echo -n .; sleep 1; done'
echo
log "Pouch started OK :-)"

while true; do
  runstamp="$(date -Iseconds | head -c-7)"
  resultsDir="perf-test-results/$runstamp"
  mkdir -p "$resultsDir"

  log "Starting tests at $runstamp..."

  log "Testing adapter: indexeddb..."
  ./scripts/playwright-perf-test "$resultsDir" indexeddb basics

  log "Testing adapter: idb..."
  ./scripts/playwright-perf-test "$resultsDir" idb       basics

  log "Results written to: $resultsDir"

  ./scripts/compare-perf-results "$runstamp"
  echo
  
  read -p "Press enter to run tests again... " -s
  echo
done
