#!/bin/bash -eu
set -o pipefail

logPrefix="$(basename "$0")"
log() {
  echo "[$logPrefix] [$(date)] $*"
}

log "Starting dev server..."
SERVER="pouchdb-express-router" # TODO what is this doing?
export COUCH_HOST="http://admin:password@127.0.0.1:5984" 

CLIENT="node" npx nodemon -w ./packages/node_modules/ -w ./tests/performance/ ./bin/dev-server.js >dev.log 2>&1 &

log "Starting couch..."
docker run -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -it --name my-couchdb -p 5984:5984 trivago/couchdb-cors:latest &

./wait-for-it.sh localhost:5984
log "Couch started OK :-)"

./wait-for-it.sh localhost:8000
log "Pouch started OK :-)"

# FIXME none of the code above actually works for starting pouch or the local server
# so to make up for it, we don't run tests until the user says they're ready
read -p "Press enter to run tests for first time... " -s

while true; do
	resultsDir="perf-test-results/$(date -Iseconds | head -c-7)"
	mkdir -p "$resultsDir"
	./scripts/playwright-perf-test "$resultsDir" idb
	./scripts/playwright-perf-test "$resultsDir" indexeddb
	log "Results written to: $resultsDir"
	echo
	
	read -p "Press enter to run tests again... " -s
	echo
done
