#!/usr/bin/env node
const { chromium, firefox, webkit } = require('playwright');

const log = (...args) => console.log(`[${new Date()}]`, 'INFO', ...args);

(async () => {
  log('launching browser...');
  const browser = await chromium.launch({ headless:false }); // Or 'firefox' or 'webkit'.
  const page = await browser.newPage();
  log('heading for perf test page...');
  await page.goto('http://127.0.0.1:8000/tests/performance/');
	// ...
  log('closing browser...');
  await browser.close();
  log('browser closed.');
})();
